make_actordef -o SCRIPT\mars_actordef.inc -i WADSRC\Mars3D\MARS3D_KEYS.txt -i WADSRC\Mars3D\MARS3D_WEAPONPICKUP.txt -i WADSRC\Mars3D\MARS3D_AMMO.txt -i WADSRC\Mars3D\MARS3D_AMMO_EXTRA.txt -i WADSRC\Mars3D\MARS3D_ARMORBONUS.txt -i WADSRC\Mars3D\MARS3D_HEALTHBONUS.txt -i WADSRC\MARS3D\MARS3D_DECORATIONS.txt -i WADSRC\MARS3D\MARS3D_DECORATIONS_EXTRA.txt -i WADSRC\MARS3D\MARS3D_OBSTACLES.txt -i WADSRC\MARS3D\MARS3D_QUESTIONMARKS.txt -i WADSRC\MARS3D\MARS3D_POWERUPS.txt -i WADSRC\MARS3D\MARS3D_POWERUPS_EXTRA.txt -i WADSRC\MARS3D\MARS3D_ENEMIES.txt -i WADSRC\MARS3D\MARS3D_ENEMIES_EXTRA.txt -i WADSRC\MARS3D\MARS3D_THINKERS.txt -i WADSRC\MARS3D\MARS3D_WEAPONS.txt -i WADSRC\MARS3D\MARS3D_GLASS.txt -i WADSRC\MARS3D\MARS3D_OTHER.txt -i WADSRC\MARS3D\MARS3D_PEOPLE.txt -i WADSRC\MARS3D\MARS3D_ITEMS.txt -i WADSRC\MARS3D\MARS3D_KEYSEQUENCES.txt
cd .\WADSRC
dir ..\..\bin\Mars3D.pk3
"C:\Program Files\7-Zip\7z.exe" a -r ..\..\bin\Mars3D.zip *.*
move ..\..\bin\Mars3D.zip ..\..\bin\Mars3D.pk3
dir ..\..\bin\Mars3D.pk3
pause